name: Ubuntu 20.04 gcc 11 x64

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI Variables
        id: vars
        run: echo "::set-output name=docker_tag::$(git rev-parse --abbrev-ref ${{ github.head_ref || github.ref || 'HEAD' }} | sed 's/[^a-z0-9_-]/__/gi')"
      - name: Build the Docker image and code
        env:
          DOCKER_IMAGE_TAG: ${{ steps.vars.outputs.docker_tag }}
        run: docker-compose run build-kr-ubuntu
